Vagrant.configure(2) do |config|
  config.vm.box = "debian/contrib-jessie64"
  config.vm.synced_folder "../projectFiles/", "/home/vagrant/euler/"
  config.vm.provision "shell", path: "./provision.sh"
end
